### ISSUE TITLE
Error while setup

### ISSUE THREAD

**Issue by dag7dev** [gbdev/homebrewhub#112]
# Issues
1. if `database-gba` is not present into `db-sources` folder, it gives error. I don't think this is a good idea, and should instead be skipped.
2. any database folder must be in the `db-sources`. This is not specified anywhere in the readme
3. during the setup database-nes is included I don't think this is a good idea as well

**Comment by avivace** [comment]
Point 2 fixed here: https://github.com/gbdev/homebrewhub/commit/4bee70b03bf12ae4c8a616b5791c90e2119c8d1e

**Comment by avivace** [comment]
Point 1 fixed here: https://github.com/gbdev/homebrewhub/commit/156485e2575d1e42e6d23729ad1f916183ae8d8b
