### ISSUE TITLE
Pixelating screenshots with CSS

### ISSUE THREAD

**Issue by NieDzejkob** [gbdev/homebrewhub#25]
See https://github.com/gbdev/homebrewhub/commit/a9c9716370be9788e9c4a31dd9ca599d6ebeedda#r34894815

**Comment by avivace** [comment]
Does it look good to you now, @NieDzejkob ?

**Comment by NieDzejkob** [comment]
The carousel looks good now, but there is a separate rule for other images, which only works on Chrome and applies to the screenshots on the Games page.

**Comment by avivace** [comment]
@NieDzejkob Looks perfectly pixelated now for me, on both Chromium and Firefox

**Comment by NieDzejkob** [comment]
Also looks right to me :+1:
