### ISSUE TITLE
"repository" field present in json files but doesn't appear in web view

### ISSUE THREAD

**Issue by AntonioND** [gbdev/homebrewhub#47]
Some games have a ``repository`` field in the json file, like https://github.com/gbdev/database/blob/40d172b7e7dbdf3ed67864768f42a379acd238ef/entries/geometrix/game.json, but it doesn't appear in the web view: https://gbhh.avivace.com/game/geometrix

**Comment by avivace** [comment]
Fixed by https://github.com/gbdev/homebrewhub/commit/c083119b45a7af9d51bc1d9cd0aaeff595090ac6
