### ISSUE TITLE
Handle NSFW flag

### ISSUE THREAD

**Issue by avivace** [gbdev/homebrewhub#61]

**Comment by dag7dev** [comment]
Adding a NSFW in "categories" could it be a good idea?

**Comment by avivace** [comment]
Why a category and not a flag?

**Comment by dag7dev** [comment]
> Why a category and not a flag?

Whoops, with category I meant "tags".

We would need to re-work the entire schema of each file, the model file, and more stuff to do.

A tag would be less intrusive (by default they are SFW, if they have "NSFW" in tags, then don't show them while querying).

**Comment by avivace** [comment]
There's a flag in the schema
