### ISSUE TITLE
Contents of the site disappear after a split sec

### ISSUE THREAD

**Issue by return2monki** [gbdev/homebrewhub#85]
In the inspector it says Cannot read properties and all the page contents disappear. The site worked for me some time ago though.

**Comment by avivace** [comment]
Uh, you are right :/ Thanks for the report, I'm investigating on how to reproduce this locally

**Comment by return2monki** [comment]
It actually just started working again now with no errors.

**Comment by avivace** [comment]
> It actually just started working again now with no errors.

Yes, I'm currently troubleshooting it. Currently it works but you can only see 10 games

**Comment by return2monki** [comment]
Oh my bad, PS the about link on github has a 3 in the link [hh3.gbdev.io](https://hh3.gbdev.io/)

**Comment by avivace** [comment]
Okay, https://github.com/gbdev/virens/commit/79519bbaf2d3000f7f25cf35ea5c8989b4c14a95 should've fixed it. https://hh.gbdev.io/ is online and serving the 1100+ entries from the database.

The hh3 link is actually correct, as that points to the backend API, but I didn't have the time to put a landing page there, while hh.gbdev.io serves the frontend.

I will change the link to the frontend while hh3 only serves the API without any information..

Thanks @return2monki !
